export const SEED_MEALS: string[] = [
  "Tarte tomate mozzarella",
  "Mozza panée salade",
  "Tarte au fromage salade",
  "Quiche salade",
  "Avocat riz thon",
  "Salade tomates avocat œuf etc",
  "Tomates cottage cheese avocat",
  "Rillettes de thon pain salade",
  "Pain poilâne avocats feta œufs brouillés bacon",
  "Pain poilâne œuf poché saumon avocat",
  "Taboulé",
  "Potage fromage",
  "Potage charcuterie",
  "Tartines de chèvre",
  "Tartines de reblochon",
  "Potage croque monsieur",
  "Croque monsieur salade",
  "Fromage salade",
  "Salade charcuterie",
  "Salade tomates cerises / mozza Buffala",
  "Tarama salade",
  "Brick salade",
  "Chèvre chaud salade",
  "Cake salade",
  "Salade de quinoa",
  "Chakchouka",
  "Poêlée courgettes",
  "Ratatouille",
  "Patates saumon",
  "Gratin de choux fleur",
  "Gratin de courgettes",
  "Fêta légumes au four",
  "Courgettes farcies au chèvre",
  "Légumes à la parmigiana",
  "Tian de légumes",
  "Salade fromage charcuterie",
  "Gratin de légumes",
  "Gratin dauphinois salade",
  "Feuilleté au jambon salade",
  "Cocottes œuf chèvre",
  "Gougères salade",
  "Wok légumes",
  "Ratatouille",
  "Carottes rôties au miel/feta + poulet citron",
  "Nuggets maison légumes",
  "Nuggets le gaulois purée",
  "Pizza",
  "Flammenkuche",
  "Rôti",
  "Haricots verts omelette",
  "Patates dans le four",
  "Poêlée légumes lardons",
  "Carottes lardons",
  "Aligot saucisses truffade",
  "Lasagnes",
  "Chili con carne",
  "Risotto",
  "Saucisse écrasé de pommes de terre",
  "Tortilla salade",
  "Tomates farcies riz",
  "Médaillons de porc",
  "Blanquette",
  "Curry de légumes",
  "Omelette",
  "Bœuf bourguignon",
  "Pates au gorgonzola",
  "Pâtes au saumon",
  "Pâtes sauce tomate ricotta",
  "Pâtes bolognaise",
  "Pâtes carbo",
  "Gratin de penne sauce tomate ricotta",
  "Pizza maison",
  "Lentilles saucisse",
  "Rösti saumon fumé",
  "Pommes de terre parmesan",
  "Fêta pâte filo",
  "Coquillettes jambon Comté",
  "Risotto de coquilettes",
  "Rosti œuf jambon / salade",
  "Steaks frites",
  "Gratin de macaronis",
  "Burgers maison",
  "Hot dog frites chips",
  "Cordon bleu boucherie",
  "Tartiflette",
  "Mont d'or pommes de terre",
  "Raclette",
  "Nouilles sautées poulet cacahuètes",
  "Saumon légumes",
  "Escalopes panées patates",
  "Gratin de coquillettes jambon",
  "Pizza maison salade",
  "Roti de porc lardons olives",
  "Poulet indien aux épices",
  "Gratin de raviolis",
  "Poulet crème coco",
  "Poulet rôti",
  "Jambon au porto",
  "Crêpes bretonnes",
  "Crêpes maison",
  "Fajitas",
  "Croissants au comté",
  "Mont d'or/pommes de terre",
  "Escalopes de poulet crème champignons",
];
